// <auto-generated />
namespace MyPhotoDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Resolutiontopicture : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resolutiontopicture));
        
        string IMigrationMetadata.Id
        {
            get { return "201804190849381_Resolution-to-picture"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
